dist: trusty
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install: pip install .
script:
  - pip install nose mock
  - 'pip download --no-deps --no-binary :all: --dest pyota-unittests --pre pyota'
  - tar -zxf pyota-unittests/PyOTA-*.tar.gz -C pyota-unittests --strip-components=1
  - nosetests pyota-unittests/test
deploy:
  on:
    branch: master
  provider: pypi
  distribution: bdist_wheel sdist
  skip_upload_docs: true
  user: phx
  password:
    secure: uprcy4uI8nx4t6NVfyzAlr5L9JgomGg6ZJbhb0u7lRUuOHeCB9ETXrg6zSbwiBGKc3bnbnAIJvGGVJErAdsOd9x5p3oyZI8UPOj9nQCKX3FStIl0x10licad1X5lO2WlIGyJNlg+uncFr3sUCG4W4SqujmDsBQnsUBVG2ei0i9eLxxzQsp+gPPPlVw2OLlkJ40B6wO64XcIf6Zlzq4Z/7mvtH3fkczPBiS6UYEv1I1OEBUaZ/h1fsvsbnriMV3Li3hdt22kquEqSxwxBjMcJ9FRAuyhJZz/GNkeHLiLkDodR3VKHan5+jBsWH44+xriOxNVhGNdI84u0NmXz00Crs5WL7O83vjM8m1t3rK1uX+fiyG7WhClFov1Lk4/OqBBUg92rXKvj1h78tSW2ldlwN6pv2QrmpZtWLDZySSPPmkDKAEQoWBo6wuotltqO9EUwi8Y4MHaXafRJcT5OaqJLa12jJTWAyAauzrO7HbcrCLJetcb1KY+ouBw7agLw30juPgm3d35mNV2jWaU2FaYr/vTGuT/PLQMOgWWoGb0LzHcLhrrv7QIBM/LZX+an02DGNHRoV7qGF5w+OLAt8eZOMuAhesZ5HTOXWj5+IXGjAupaJ/9cOYnSM7OwUjXcOh7I/5dvx41wV6sxDuI0jiIqCN47ZpSyA33FnCpjfrs6wTM=
